baseURL: http://eamonburns.com/novuscript/
languageCode: en-us
title: Novuscript
theme: novuscript

menu:
  main:
    - name: Home
      pre: home
      url: /
      weight: 1

    - name: Posts
      pre: pen-tool
      url: /posts/
      weight: 2

    - name: Tags
      pre: tag
      url: /tags/
      weight: 3
